import ameniphoto from "../../images/ameniphoto.png";
import voiceClip from "../../traslatorsVoices/audio_clip_voice_ameni.mp3";
import voiceClipExemple from "../../traslatorsVoices/audio_clip_voice_exemple.mp3";

const femaleAnonymous =
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKQjEx8kXBBc6MKztnNLjEAPnNcIEy6NdctUzVPsORZ8uxU60SyZm3voVUUPRiB5nE6Q&usqp=CAU";
const maleAnonymous =
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdheCR0hojCQAfcWPEjeejJF5T5iRAxbZniSYbXrUybYFxrdQuHTU3F7mmcNyTjTeJMw&usqp=CAU";
const dummyCards = [
  {
    firstname: "Ameni",
    lastname: "Hassen",
    type: "Freelancer",
    email: "amenihassen8@gmail.com",
    phoneNumber: "56083746",
    location: "Sousse",
    languages: "English Arabic Frensh",
    photoUrl: ameniphoto,
    voiceClip: voiceClip,
    availabilityBattery: 4,
  },
  {
    firstname: "Alice",
    lastname: "Smith",
    type: "Translator",
    email: "alice@example.com",
    phoneNumber: "555-5678",
    location: "Los Angeles",
    languages: "French English",
    photoUrl: femaleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 3,
  },
  {
    firstname: "Michael",
    lastname: "Johnson",
    type: "Translator",
    email: "michael@example.com",
    phoneNumber: "555-9012",
    location: "Chicago",
    languages: "German English",
    photoUrl: maleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 2,
  },
  {
    firstname: "Emily",
    lastname: "Brown",
    type: "Translator",
    email: "emily@example.com",
    phoneNumber: "555-3456",
    location: "Houston",
    languages: "Spanish English",
    photoUrl: femaleAnonymous,
    voiceClip: undefined,
    availabilityBattery: 1,
  },
];

const dummyCards_Legal = [
  {
    firstname: "Ameni",
    lastname: "Hassen",
    type: "Freelancer",
    email: "amenihassen8@gmail.com",
    phoneNumber: "56083746",
    location: "Sousse",
    languages: "English Arabic Frensh",
    photoUrl: ameniphoto,
    voiceClip: voiceClip,
    availabilityBattery: 4,
  },
  {
    firstname: "Alice",
    lastname: "Smith",
    type: "Legal Translator",
    email: "alice@example.com",
    phoneNumber: "555-5678",
    location: "Los Angeles",
    languages: "French English",
    photoUrl: femaleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 3,
  },
  {
    firstname: "Michael",
    lastname: "Johnson",
    type: "Legal Translator",
    email: "michael@example.com",
    phoneNumber: "555-9012",
    location: "Chicago",
    languages: "German English",
    photoUrl: maleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 2,
  },
  {
    firstname: "Emily",
    lastname: "Brown",
    type: "Legal Translator",
    email: "emily@example.com",
    phoneNumber: "555-3456",
    location: "Houston",
    languages: "Spanish English",
    photoUrl: femaleAnonymous,
    voiceClip: undefined,
    availabilityBattery: 1,
  },
];

const dummyCards_Technical = [
  {
    firstname: "Ameni",
    lastname: "Hassen",
    type: "Freelancer",
    email: "amenihassen8@gmail.com",
    phoneNumber: "56083746",
    location: "Sousse",
    languages: "English Arabic Frensh",
    photoUrl: ameniphoto,
    voiceClip: voiceClip,
    availabilityBattery: 4,
  },
  {
    firstname: "Alice",
    lastname: "Smith",
    type: "Technical Translator",
    email: "alice@example.com",
    phoneNumber: "555-5678",
    location: "Los Angeles",
    languages: "French English",
    photoUrl: femaleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 3,
  },
  {
    firstname: "Michael",
    lastname: "Johnson",
    type: "Technical Translator",
    email: "michael@example.com",
    phoneNumber: "555-9012",
    location: "Chicago",
    languages: "German English",
    photoUrl: maleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 2,
  },
  {
    firstname: "Emily",
    lastname: "Brown",
    type: "Technical Translator",
    email: "emily@example.com",
    phoneNumber: "555-3456",
    location: "Houston",
    languages: "Spanish English",
    photoUrl: femaleAnonymous,
    voiceClip: undefined,
    availabilityBattery: 1,
  },
];
const dummyCards_Certified = [
  {
    firstname: "Ameni",
    lastname: "Hassen",
    type: "Certified Translator",
    email: "amenihassen8@gmail.com",
    phoneNumber: "56083746",
    location: "Sousse",
    languages: "English Arabic Frensh",
    photoUrl: ameniphoto,
    voiceClip: voiceClip,
    availabilityBattery: 4,
  },
  {
    firstname: "Alice",
    lastname: "Smith",
    type: "Certified Translator",
    email: "alice@example.com",
    phoneNumber: "555-5678",
    location: "Los Angeles",
    languages: "French English",
    photoUrl: femaleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 3,
  },
  {
    firstname: "Michael",
    lastname: "Johnson",
    type: "Certified Translator",
    email: "michael@example.com",
    phoneNumber: "555-9012",
    location: "Chicago",
    languages: "German English",
    photoUrl: maleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 2,
  },
  {
    firstname: "Emily",
    lastname: "Brown",
    type: "Certified Translator",
    email: "emily@example.com",
    phoneNumber: "555-3456",
    location: "Houston",
    languages: "Spanish English",
    photoUrl: femaleAnonymous,
    voiceClip: undefined,
    availabilityBattery: 1,
  },
];
const dummyCards_Interpretor = [
  {
    firstname: "Ameni",
    lastname: "Hassen",
    type: "Freelancer",
    email: "amenihassen8@gmail.com",
    phoneNumber: "56083746",
    location: "Sousse",
    languages: "English Arabic Frensh",
    photoUrl: ameniphoto,
    voiceClip: voiceClip,
    availabilityBattery: 4,
  },
  {
    firstname: "Alice",
    lastname: "Smith",
    type: "Interpretor",
    email: "alice@example.com",
    phoneNumber: "555-5678",
    location: "Los Angeles",
    languages: "French English",
    photoUrl: femaleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 3,
  },
  {
    firstname: "Michael",
    lastname: "Johnson",
    type: "Interpretor",
    email: "michael@example.com",
    phoneNumber: "555-9012",
    location: "Chicago",
    languages: "German English",
    photoUrl: maleAnonymous,
    voiceClip: voiceClipExemple,
    availabilityBattery: 2,
  },
  {
    firstname: "Emily",
    lastname: "Brown",
    type: "Interpretor",
    email: "emily@example.com",
    phoneNumber: "555-3456",
    location: "Houston",
    languages: "Spanish English",
    photoUrl: femaleAnonymous,
    voiceClip: undefined,
    availabilityBattery: 1,
  },
];
export {
  dummyCards,
  dummyCards_Legal,
  dummyCards_Technical,
  dummyCards_Certified,
  dummyCards_Interpretor,
};
